### ISSUE TITLE
LDAP Setup

### ISSUE THREAD

**Issue by Dargmuesli** [flipdot/drinks-scanner-display#35]
The README states that LDAP should be reachable via `ldap://rail/`, but the linked `users.py` uses `flipdot.org` as far as I can see. Is the README wrong about that?

Also, now that we have PostgreSQL database dumps: is there something similar for LDAP?

**Comment by cfstras** [comment]
I only see your change to move rail.fd out into config.py -- flipdot.org is only used in the identifiers.
there might be, in openLDAP. But since our schema is fairly standard, I don't know whether we need it...
although for local testing it would be very helpful. maybe make a docker-compose file with postgres, ldap and some useful testing data?

**Comment by Dargmuesli** [comment]
Yep, that was my plan :)
I never used LDAP before, so I don't know if there is any standard setup or something alike.

**Comment by Dargmuesli** [comment]
Docker stack files are now added and detailed instructions on how to get started can be found in the README.
